#!/bin/sh

set -e
daemon_cert_root=/certs

# Make sure the certificate and private key files are
# never world readable, even just for an instant while
# we're copying them into daemon_cert_root.
umask 077

cp -a -H --force "$RENEWED_LINEAGE/fullchain.pem" "$daemon_cert_root/fullchain.pem"
cp -a -H --force "$RENEWED_LINEAGE/privkey.pem" "$daemon_cert_root/privkey.pem"

# Apply the proper file ownership and permissions for
# the daemon to read its certificate and key.
chown -R root. "$daemon_cert_root/*"
chmod 644 "$daemon_cert_root/fullchain.pem"
chmod 600 "$daemon_cert_root/privkey.pem"