# MTA stack
#  
# Usage:
# docker stack init --advertise-addr=IP
#
# docker stack deploy -c ./mta-stack.yml mta

version: '3.6'
services:

  mail-relay:
    image: smugljanka/postfix-relay-opendkim
    deploy:
      replicas: 1
      restart_policy:
        condition: none
#    ports:
#      - "25:25"
    volumes:
      - postfix-pool:/var/spool/postfix
      - ./scripts/01_init_postfix.sh:/docker-entrypoint.d/01_init_postfix.sh
      - ./scripts/02_init_rsyslog.sh:/docker-entrypoint.d/02_init_rsyslog.sh
    environment:
      TZ: UTC
      POSTFIX_HOSTNAME: mx.<YOUR_MAIL_DOMAIN>
      POSTFIX_DOMAIN: <YOUR_MAIL_DOMAIN>
      POSTFIX_NETWORKS: ''
      DKIM_ADDRESS: mail-dkim
      DKIM_PORT: 14999
    entrypoint: ["/docker-entrypoint.sh"]
    command: ["postfix", "start-fg"]
    healthcheck:
      test: ps aux | grep 'master' || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-net

  mail-dkim:
    image: smugljanka/postfix-relay-opendkim
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    secrets:
      - source: domain-dkim-key
        target: domain.private
        mode: 600
        uid: "100"
        gid: "101"
    volumes:
      - ./scripts/01_init_opendkim.sh:/docker-entrypoint.d/01_init_opendkim.sh
      - ./scripts/02_init_rsyslog.sh:/docker-entrypoint.d/02_init_rsyslog.sh
    environment:
      TZ: UTC
      POSTFIX_DOMAIN: <YOUR_MAIL_DOMAIN>
      POSTFIX_NETWORKS_REGEXP_MAP: '10.*.*.*'
      DKIM_SELECTOR: <YOUR_DKIM_SELECTOR>
      DKIM_PORT: 14999
    entrypoint: ["/docker-entrypoint.sh"]
    command: ["opendkim", "-f", "-l"]
    healthcheck:
      test: ps aux | grep 'opendkim' || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - app-net

volumes:
  postfix-pool:

networks:
  app-net:
    external: true

secrets:
  domain-dkim-key:
    file: ./path/to/your.domain.com.priv
