production:
  email_delivery:
    delivery_method: :async_smtp
    async_smtp_settings:
        address: mail-relay
        port: 25
        authentication: :nil
        domain: bolyshev.com

#production:
#  email_delivery:
#    delivery_method: :async_smtp
#    async_smtp_settings:
#        address: 172.17.0.1
#        port: 25
#        authentication: :nil
#        domain: bolyshev.com