production:
  email_delivery:
    delivery_method: :async_smtp
    async_smtp_settings:
        address: 172.17.0.1
        port: 25
        authentication: :nil
        domain: rm.bolyshev.com

#production:
#  email_delivery:
#    delivery_method: :async_smtp
#    async_smtp_settings:
#        address: redmine-mta
#        port: 25
#        authentication: :login
#        domain: rm.bolyshev.com
#        user_name: redmine@rm.bolyshev.com
#        password: St45Swq1K

